[connections.workflow]
account = "{{ SNOWFLAKE_ACCOUNT }}"
user = "{{ SNOWFLAKE_DEVOPS_USER }}"
role = "{{ SNOWFLAKE_DEVOPS_ROLE }}"
authenticator = "{{ SNOWFLAKE_DEFAULT_AUTHENTICATOR }}"
warehouse = "{{ SNOWFLAKE_DEVOPS_WAREHOUSE }}"
database = "{{ SNOWFLAKE_DEVOPS_DB }}"
schema = "{{ SNOWFLAKE_DEVOPS_SCHEMA }}"
private_key_file = "rsa_key.p8"